### PR TITLE
Makefile encoding

### PR DESCRIPTION
**Pull request by michelk**
Hi Nicolas,
do you mind considering Makefile rendering?
Cheers, Michel

### CODE REVIEW

**Comment by nmattia** [comment]
Hi Michel,

Thanks for the PR. I think it's a great idea. It generally looks good, I have a few thoughts though:

1. You could even bump to LTS 8
1. I wonder if another kind of `Assignment` would be needed. Currently here's what happens: 

``` haskell
parse "foo:=bar" == Assignment "foo" "bar" == parse "foo=bar" => encode . parse /= id
```
 which is not ideal. I'm tempted to merge this PR already and have a think about it during the week. Thoughts?

**Comment by michelk** [comment]
Nicolas,
I just updated stack.yaml to LTS 8.

And you are right, the assignment is not ideal.

**Comment by nmattia** [comment]
@michelk I can't see the LTS version bump, but it's alright. I'll merge this as-is.

**Comment by nmattia** [comment]
Thanks a lot :)

**Comment by michelk** [comment]
Oh, something went wrong with 'amend'. 

Thanks for merging and for the very helpful library.

**Pull request merged**
